---
- hosts: all

  tasks:

  - name: Check if reboot is required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Rebooting machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    when: reboot_required_file.stat.exists
