- name: Intégration du serveur dans le Domaine
  hosts: all
  gather_facts: no
  tasks: Join
  - win_domain_membership:
      dns_domain_name: '{{ domain_name }}' 
      hostname: mydomainclient
      domain_admin_user: '{{ domain_admin }}' 
      domain_admin_password: '{{ domainadmin_pwd }}' 
      state: domain
    register: domain_state

  - win_reboot: Wait reboot
    when: domain_state.reboot_required
