- name: Applicaiton de la configuration de base sur Windows server 
  hosts: all
  tasks:
    - name: Changement du mot de passe du compte Administrator local
      win_user:
        name: Administrator
        password:  "{{ Localadminnewpassword }}"
        state: present
        update_password: always
      no_log: True
      async: 0
      poll: 0
